### ISSUE TITLE
AttributeError: 'EasyDocumentEmbeddings' object has no attribute 'rnn_embeddings'

### ISSUE THREAD

**Issue by blerstpub** [Novetta/adaptnlp#100] opened 2020-12-30 17:36 UTC
Cannot use pool option to generate embeddings (instead of the default rnn).

A snippet for the problem: 

```
embedding_type='albert-xxlarge-v2'
embedding_methods=["pool"]
doc_embeddings = EasyDocumentEmbeddings(embedding_type, methods = embedding_methods)

```

This is the error I get:

```
  File "env/lib/python3.7/site-packages/adaptnlp/training.py", line 91, in __init__
   self._initial_setup(self.label_dict, **kwargs)
 File "env/lib/python3.7/site-packages/adaptnlp/training.py", line 97, in _initial_setup
   document_embeddings: DocumentRNNEmbeddings = self.encoder.rnn_embeddings
AttributeError: 'EasyDocumentEmbeddings' object has no attribute 'rnn_embeddings'
```

Expected behavior would be to successfully obtain an easy document embeddings object with no errors

Running on debian buster, python3.7

If someone could give me a fix or a workaround or if I'm using this incorrectly, then please let me know

**Comment by blerstpub** [comment] 2021-01-04 15:14
Nobody? Maybe I'm not using this correctly or perhaps there's a fix required, either way it would be helpful if someone could respond to this

**Comment by aychang95** [comment] 2021-01-04 15:39
Hi @blerstpub 
Sorry about the wait, we've been caught up during the holidays and I wish I could've gotten to this sooner!

What version of adaptnlp is this? Are you installing from source?

I tried to replicate the issue with your snippet using v0.2.1, but that seems to work without a hitch. I did notice that you're using the `SequenceClassifierTrainer` module which has been replaced with the built-in trainer in the `EasySequenceClassifier` module. You can find details on training in the docs here: https://novetta.github.io/adaptnlp/tutorial/sequence-classification.html

The `SequenceClassifierTrainer` will be deprecated in the near future as we're pushing pretty large updates to adaptnlp for a 1.0 release. I should have made that more clear however, sorry about that!

**Comment by muellerzr** [comment] 2021-03-03 20:21
@blerstpub I'm closing this issue as I can't reproduce it. If you can include a full reproducer as well as what version of the library you're using, feel free to re-open this issue and @ me.

**Closed by muellerzr** 2021-03-03 20:21 UTC
